[package]
name = "lapjv"
version = "0.1.2"
authors = ["Andrii Dmytrenko <andrii.dmytrenko@deliveroo.co.uk>"]
description = "Linear Assignmment Problem solve using Jonker-Volgenant algorithm"
license = "MIT"
documentation = "https://docs.rs/lapjv"
homepage = "https://github.com/Antti/lapjv-rust"
repository = "https://github.com/Antti/lapjv-rust.git"

include = [
    "**/*.rs",
    "Cargo.toml",
    "README.md"
]

[profile.release]
debug = true
lto = false

[badges]
travis-ci = { repository = "Antti/lapjv-rust", branch = "master" }
maintenance = { status = "as-is" }

[features]
nightly = []

[dependencies]
ndarray = "0.12"
num-traits = "0.1"
log = { version = "0.4", features = ["max_level_debug", "release_max_level_warn"] }


[dev-dependencies]
csv = "1.0"
pretty_assertions = "0.6"
rand = "0.6"
rustc_version = "0.2"
serde = "1.0"